[package]
name = "ed25519_vanity"
version = "0.1.0"
edition = "2024"

[dependencies]
cust = { git = "https://github.com/Rust-GPU/Rust-CUDA.git" }
hex = "0.4.3"
rand = "0.8"

[build-dependencies]
# christian's branch
cuda_builder = { git = "https://github.com/LegNeato/Rust-CUDA.git", rev = "5f81c65950166abd48cd3b94b01564538a281008" }

# normal
#cuda_builder = { git = "https://github.com/Rust-GPU/Rust-CUDA.git" }
