[package]
name = "ed25519_vanity"
version = "0.1.0"
edition = "2024"

[dependencies]
cust = { git = "https://github.com/LegNeato/Rust-CUDA.git", rev = "9026816330a8745df7bf1bf9f7ad21889f7375f0" }
#cust = { git = "https://github.com/Rust-GPU/Rust-CUDA.git" }
hex = "0.4.3"
rand = "0.8"

[build-dependencies]
cuda_builder = { git = "https://github.com/LegNeato/Rust-CUDA.git", rev = "9026816330a8745df7bf1bf9f7ad21889f7375f0" }
#cuda_builder = { git = "https://github.com/Rust-GPU/Rust-CUDA.git" }
