[package]
name = "ed25519_vanity_kernels"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cuda_std = { git = "https://github.com/Rust-GPU/Rust-CUDA.git" }
ed25519-dalek = { version = "2.1.1", default-features = false }
bs58 = { path = "./deps/bs58-rs", default-features = false }

[build-dependencies]
cuda_builder = { git = "https://github.com/Rust-GPU/Rust-CUDA.git" }
