[package]
name = "ed25519_vanity_kernel"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cuda_std = { git = "https://github.com/Rust-GPU/Rust-CUDA.git" }
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
ed25519 = { path = "../ed25519" }

[build-dependencies]
cuda_builder = { git = "https://github.com/Rust-GPU/Rust-CUDA.git" }
