[package]
name = "ed25519_vanity_kernel"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cuda_std = { git = "https://github.com/Rust-GPU/Rust-CUDA.git" }
bs58 = { version = "0.5.1", default-features = false }
rand_core = { version = "0.9.3" }
rand_xorshift = { version = "0.4.0", default-features = false }

[build-dependencies]
cuda_builder = { git = "https://github.com/Rust-GPU/Rust-CUDA.git" }
