[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cuda_std = { git = "https://github.com/LegNeato/Rust-CUDA.git", rev = "6a3b08bfaa3c3441f7e3d8a522ad444d794e35b5" }
curve25519-dalek = { version = "4.1.3", default-features = false, features = ["alloc", "precomputed-tables"] }

#cuda_std = { git = "https://github.com/Rust-GPU/Rust-CUDA.git" }
#curve25519-dalek = { git = "https://github.com/brandonros/curve25519-dalek.git", rev = "5c453288e39eed68697c3a689f7adf14a3a93ef3", default-features = false, features = ["alloc", "precomputed-tables", "cuda"] }
