[package]
name = "ed25519_vanity_kernel"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cuda_std = { git = "https://github.com/Rust-GPU/Rust-CUDA.git" }
gpu_rand = { git = "https://github.com/Rust-GPU/Rust-CUDA.git" }
hmac-sha512 = { path = "./deps/rust-hmac-sha512", default-features = false }
ed25519-compact = { path = "./deps/rust-ed25519-compact", default-features = false, features = ["cuda"] }
bs58 = { version = "0.5.1", default-features = false }

[build-dependencies]
cuda_builder = { git = "https://github.com/Rust-GPU/Rust-CUDA.git" }
