[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cuda_std = { git = "https://github.com/LegNeato/Rust-CUDA.git", rev = "9026816330a8745df7bf1bf9f7ad21889f7375f0" }
#curve25519-dalek = { git = "https://github.com/brandonros/curve25519-dalek.git", rev = "5c453288e39eed68697c3a689f7adf14a3a93ef3", default-features = false, features = ["alloc", "precomputed-tables", "cuda"] }
curve25519-dalek = { version = "4.1.3", default-features = false, features = ["alloc", "precomputed-tables"] }

[build-dependencies]
cuda_builder = { git = "https://github.com/LegNeato/Rust-CUDA.git", rev = "9026816330a8745df7bf1bf9f7ad21889f7375f0" }
